USE QLDA
--TAO BANG NHAN VIEN
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(5) PRIMARY KEY,
	HONV NVARCHAR(20),
	TENLOT NVARCHAR(20),
	TENNV NVARCHAR(10),
	NGAYSINH DATE,
	DIACHI NVARCHAR(100),
	PHAI VARCHAR(5),
	LUONG DECIMAL(10,2),
	MAPB VARCHAR(5)
)
--KET THUC TAO BANG NHAN VIEN
--TAO BANG THAN NHAN
GO
CREATE TABLE THANNHAN
(
 MANV VARCHAR(5) NOT NULL,
 TENTN NVARCHAR (30) NOT NULL,
 PHAI VARCHAR(5),
 NGAYSINH DATE,
 QUANHE NVARCHAR(20),
 PRIMARY KEY(MANV,TENTN)
)
GO
--TAO KHOA NGOAI CUA BANG THAN NHAN  SAU KHI TAO BANG THAN NHAN
ALTER TABLE THANNHAN ADD CONSTRAINT FK_THANNHAN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
-- END TAO KHOA NGOAI CUA BANG THAN NHAN  SAU KHI TAO BANG THAN NHAN
--TAO BANG PHONG BAN
GO
CREATE TABLE PHONGBAN
(
	MAPB VARCHAR(5) PRIMARY KEY,
	TENPB NVARCHAR(50),
	TRUONGPHONG VARCHAR(5),
	NG_NHANCHUC DATE,
	--FOREIGN KEY(MaBM) REFERENCES BoMon(MaBM)--
)
GO
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
--END TAO BANG PHONG BAN
--TAO BANG DE AN

--END TAO BANG DE AN